DROP TABLE IF EXISTS CUSTOMER;
 
CREATE TABLE CUSTOMER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250),
  EMAIL VARCHAR(250),
  GENDER VARCHAR(250)
);

INSERT INTO CUSTOMER VALUES(1,'Ash','ash@smail.com','male');

DROP TABLE IF EXISTS PRODUCT;
 
CREATE TABLE PRODUCT (
  PID INT AUTO_INCREMENT  PRIMARY KEY,
  PRODUCT_NAME VARCHAR(250),
  QTY INT,
  PRICE INT,
  CP_FK INT,
  CONSTRAINT FK_S FOREIGN KEY (CP_FK) REFERENCES CUSTOMER(ID)
);
INSERT INTO PRODUCT VALUES(1,'soap',2,12,1);